# 情緒到臉部表情的映射
EMOTION_TO_MORPH_TARGETS = {
    "happy": {
        "browInnerUp": 0.7,
        "eyeSquintLeft": 0.3,
        "eyeSquintRight": 0.3,
        "mouthSmileLeft": 0.9,
        "mouthSmileRight": 0.9,
        "cheekSquintLeft": 0.6,
        "cheekSquintRight": 0.6
    },
    "sad": {
        "browInnerUp": 0.8,
        "mouthFrownLeft": 0.7,
        "mouthFrownRight": 0.7,
        "browOuterUpLeft": 0.2,
        "browOuterUpRight": 0.2,
        "eyeBlinkLeft": 0.2,
        "eyeBlinkRight": 0.2
    },
    "angry": {
        "browDownLeft": 0.8,
        "browDownRight": 0.8,
        "eyeSquintLeft": 0.6,
        "eyeSquintRight": 0.6,
        "jawForward": 0.4,
        "mouthFrownLeft": 0.7,
        "mouthFrownRight": 0.7
    },
    "surprised": {
        "browInnerUp": 0.9,
        "browOuterUpLeft": 0.8,
        "browOuterUpRight": 0.8,
        "eyeWideLeft": 0.9,
        "eyeWideRight": 0.9,
        "jawOpen": 0.5,
        "mouthOpen": 0.6
    },
    "neutral": {
        "browInnerUp": 0,
        "browOuterUpLeft": 0,
        "browOuterUpRight": 0,
        "browDownLeft": 0,
        "browDownRight": 0,
        "eyeSquintLeft": 0,
        "eyeSquintRight": 0,
        "eyeWideLeft": 0,
        "eyeWideRight": 0,
        "eyeBlinkLeft": 0,
        "eyeBlinkRight": 0,
        "cheekSquintLeft": 0,
        "cheekSquintRight": 0,
        "mouthSmileLeft": 0,
        "mouthSmileRight": 0,
        "mouthFrownLeft": 0,
        "mouthFrownRight": 0,
        "mouthOpen": 0,
        "jawOpen": 0,
        "jawForward": 0
    }
}

# 預設表情
PRESET_EXPRESSIONS = {
    "happy": {
        "browInnerUp": 0.3,
        "mouthSmileLeft": 0.8,
        "mouthSmileRight": 0.8,
        "eyeSquintLeft": 0.3,
        "eyeSquintRight": 0.3,
        "cheekSquintLeft": 0.5,
        "cheekSquintRight": 0.5
    },
    "sad": {
        "browInnerUp": 0.7,
        "browOuterUpLeft": 0.2,
        "browOuterUpRight": 0.2,
        "mouthFrownLeft": 0.6,
        "mouthFrownRight": 0.6,
        "mouthLowerDownLeft": 0.4,
        "mouthLowerDownRight": 0.4
    },
    "angry": {
        "browDownLeft": 0.7,
        "browDownRight": 0.7,
        "noseSneerLeft": 0.5,
        "noseSneerRight": 0.5,
        "eyeSquintLeft": 0.5,
        "eyeSquintRight": 0.5,
        "mouthStretchLeft": 0.3,
        "mouthStretchRight": 0.3
    },
    "surprised": {
        "browInnerUp": 0.8,
        "browOuterUpLeft": 0.6,
        "browOuterUpRight": 0.6,
        "eyeWideLeft": 0.7,
        "eyeWideRight": 0.7,
        "jawOpen": 0.5
    },
    "reset": {
        "browDownLeft": 0.0,
        "browDownRight": 0.0,
        "browInnerUp": 0.0,
        "browOuterUpLeft": 0.0,
        "browOuterUpRight": 0.0,
        "cheekPuff": 0.0,
        "cheekSquintLeft": 0.0,
        "cheekSquintRight": 0.0,
        "eyeBlinkLeft": 0.0,
        "eyeBlinkRight": 0.0,
        "eyeLookDownLeft": 0.0,
        "eyeLookDownRight": 0.0,
        "eyeLookInLeft": 0.0,
        "eyeLookInRight": 0.0,
        "eyeLookOutLeft": 0.0,
        "eyeLookOutRight": 0.0,
        "eyeLookUpLeft": 0.0,
        "eyeLookUpRight": 0.0,
        "eyeSquintLeft": 0.0,
        "eyeSquintRight": 0.0,
        "eyeWideLeft": 0.0,
        "eyeWideRight": 0.0,
        "jawForward": 0.0,
        "jawLeft": 0.0,
        "jawOpen": 0.0,
        "jawRight": 0.0,
        "mouthClose": 0.0,
        "mouthDimpleLeft": 0.0,
        "mouthDimpleRight": 0.0,
        "mouthFrownLeft": 0.0,
        "mouthFrownRight": 0.0,
        "mouthFunnel": 0.0,
        "mouthLeft": 0.0,
        "mouthLowerDownLeft": 0.0,
        "mouthLowerDownRight": 0.0,
        "mouthPressLeft": 0.0,
        "mouthPressRight": 0.0,
        "mouthPucker": 0.0,
        "mouthRight": 0.0,
        "mouthRollLower": 0.0,
        "mouthRollUpper": 0.0,
        "mouthShrugLower": 0.0,
        "mouthShrugUpper": 0.0,
        "mouthSmileLeft": 0.0,
        "mouthSmileRight": 0.0,
        "mouthStretchLeft": 0.0,
        "mouthStretchRight": 0.0,
        "mouthUpperUpLeft": 0.0,
        "mouthUpperUpRight": 0.0,
        "noseSneerLeft": 0.0,
        "noseSneerRight": 0.0
    }
} 